### ISSUE TITLE
payload validation & encode/decode configurable

### ISSUE THREAD

**Issue by boxxxie** [ivarref/yoltq#1]
I'm interested adding a schema and encoder/decoders to my queues, as well as being able to save data to datomic without being forced to have the payload be a string, using a ref. also i would like a configurable db/id function (so i can use db partitions per queue)

looking at the code i think these features should be very easy to add. i'm wondering if you have tried making the queue save objects to the db instead of strings, and if you ran into issues with that approach? if not would you be interested in PRs related to the above?

**Comment by ivarref** [comment]
Hi @boxxxie 

_i'm wondering if you have tried making the queue save objects to the db instead of strings, and if you ran into issues with that approach?_

No, I didn't try that. What exactly do you mean by objects? What kind of objects would you like to store that are not `pr-str`-able? Do you have an example?

I agree that storing a `ref` would be a normal use case. Entities that already exist in the database could be stored as a simple string using the lookup-ref style, e.g. `[:some/id "123"]`, but new entities that are part of the same transaction as `yq/put` are not possible to refer as of now. I think the latter would be a fine feature to add.

_configurable db/id function (so i can use db partitions per queue)_
I don't know much about partiotions in datomic, but this sounds fine to me.

PR is welcome, but first let's discuss a little further.

**Comment by ivarref** [comment]
Hi again @boxxxie 

Not sure if you made any attempts at adding these features.

Anyways I just read about [Pitfalls and bumps in Clojure's Extensible Data Notation (EDN)](https://nitor.com/en/articles/pitfalls-and-bumps-clojures-extensible-data-notation-edn) so I'm more inclined towards adding an encode/decode option if I have time some day. You are also welcome to make a PR of course.

**Comment by boxxxie** [comment]
hey, sorry for the lack of PR.
i looked at the code and found that it was going to be a lot more work than i anticipated, to do what i thought i wanted, and i figured what you had was mostly good, with only some small changes that i think would give a lot of benefit (like removing history, or changing the payload to bytes instead of a string, which would allow saving nippy, or other more general types of data, and partition use.

partitions are pretty simple in datomic, here is part of a transact that i use to make a partition for email related data. 
then to generate ids that use that partition there

```clojure
(d/transact conn [   
{:db/id "email-campaigns" :db/ident :email-campaigns}
   [:db/add :db.part/db :db.install/partition "email-campaigns"]
])
```

https://docs.datomic.com/on-prem/schema/schema.html#partitions

and here is an example of making a new ID for a partition

```clojure
(d/tempid :email-campaigns)
;; => #datomic.db.DbId{:part :email-campaigns, :idx -1004855}
```
so, pretty simple, but the datomic docs don't really make it easy to figure that out.

if you safe the data as bytes, then an encoder/decoder is very simple to add, and stuff like nippy allows for saving java objects, which are pretty common when working with clojure. not having to figure out how to change your date/time vals to #insts, which are java.util.date, is annoying considering all the different ways java can do dates. also this allows for much more interesting validation options, if the use wants that.

saving the payload as a datomic ref would require the user to hook into how data is saved/updated, not just encoding/decoding, and i'm doing something like that on a project i'm working on, where i have a schema + custom deep-merge function that is able to generate proper upserts for datomic, including retracts and retract-entity. i think that's probably overkill for most people, and would require the user to make their own code that generates proper transactions.

Another problem is that if all the queue is doing is saving a ref, and the user is allowed to do whatever they want with it, the queue would probably have to add some concept for if it returns an ent that is allowed to be changed over time, or is static (most sensible use case for a queue). datomic is good at doing that, but it would increase the barrier to entry.

sorry, right now i don't have much time to work on something like this, i ended up using a very light weight queue interface, with some datomic as a way of referencing items in that queue, but i think i'll end up adapting the interface to use datomic... once i have more demand on my queue. i can do non-coding stuff, though, as it takes a lot less energy, and i think this library is pretty cool. until i have some more free time.

**Comment by ivarref** [comment]
Hi once again @boxxxie 

I finally added these features (as I'm finally learning about partitions today).
Hope you like it :)
Kind regards.
